objects/Attendee__c.object
<CustomObject>
    <description>Record of all Attendee</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Company Name where the Attendee belongs</description>
        <inlineHelpText>ex. ABC Company</inlineHelpText>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address of the Attendee</description>
        <inlineHelpText>ex. email@gmail.com</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Contact Number of the Attendee</description>
        <inlineHelpText>ex. 09672688171</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <description>Record of all Attendees in an event</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Attendee of the Event</description>
        <inlineHelpText>Select appropriate Event attendee</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_ProFit__c</fullName>
        <description>Defines the event</description>
        <inlineHelpText>Select appropriate Event</inlineHelpText>
        <label>Event(ProFit)</label>
        <referenceTo>Event_Profit__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if the event is Live</description>
        <inlineHelpText>Is event is Live or Not?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Maximum person for the event</description>
        <inlineHelpText>Maximum number of attendees for the event</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SendEmailToAEventAttendee_Test.cls
@isTest
private class SendEmailToAEventAttendee_Test{

    //Mock Creation: new Event Record
    Static Id createTestEventId(){
    
        Event_Profit__c evt = new Event_Profit__c();
        evt.Name = 'Test Event';
        evt.Live__c = true;
        evt.Start_Date_Time__c = datetime.newInstance(2021, 7, 21, 19, 30, 0);
        evt.End_Date_Time__c = datetime.newInstance(2021, 7, 22, 19, 30, 0);
        evt.Max_Seats__c = 10;
        
        insert evt;
        System.debug('evt.Id == ' + evt.Id );
        return evt.Id;
    }

    //Create new Attendee Record
    Static Id createTestAttendeeId(){
        Attendee__c attn = new Attendee__c();
        attn.Name = 'Test Attendee';
        attn.Company_Name__c = 'Test Company';
        attn.Email__c = 'testemail@gmail.com';
        attn.Phone__c = '09672688177';

        insert attn;
        System.debug('attn.Id == '+ attn.Id);
        return attn.Id;
    }


    @isTest
    Static void checkEventAttendee(){
        Test.startTest();

        Event_Attendee__c eAttendee = new Event_Attendee__c();
        eAttendee.Event_ProFit__c = createTestEventId();
        eAttendee.Attendee__c = createTestAttendeeId();

        insert eAttendee;

        System.debug('eAttendee.Id == ' + eAttendee.Id);
        
        //Check if successful if the record inserted and retrieved are equal
        Event_Attendee__c retrievedEAttn = [SELECT Event_ProFit__c FROM Event_Attendee__c WHERE Event_ProFit__c =: eAttendee.Event_ProFit__c];

        Test.stopTest();
            
        System.assertEquals(eAttendee.Event_ProFit__c,retrievedEAttn.Event_ProFit__c);
    }
}