objects/Attendee__c.object
<CustomObject>
    <description>Record of all Attendee</description>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <description>Record of all Attendees in an event</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Attendee of the Event</description>
        <inlineHelpText>Select appropriate Event attendee</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_ProFit__c</fullName>
        <description>Defines the event</description>
        <inlineHelpText>Select appropriate Event</inlineHelpText>
        <label>Event(ProFit)</label>
        <referenceTo>Event_Profit__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if the event is Live</description>
        <inlineHelpText>Is event is Live or Not?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Maximum person for the event</description>
        <inlineHelpText>Maximum number of attendees for the event</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AttendeeEventService_Test.cls
@IsTest
public with sharing class AttendeeEventService_Test {

    //Creating New Event
    static Id createTestNewEvent(){
        Event_Profit__c evt = new Event_Profit__c();
        evt.Name = 'Test Event';
        evt.Live__c = true;
        evt.Start_Date_Time__c = datetime.newInstance(2021, 7, 25, 19, 30, 0);
        evt.End_Date_Time__c = datetime.newInstance(2021, 7, 26, 19, 30, 0);
        evt.Max_Seats__c = 50;

        insert evt;
        // System.debug('evt.Id == ' + evt.Id );
        return evt.Id;
    }
    //Creating Old Event
    static Id createTestOldEvent(){
        Event_Profit__c evt = new Event_Profit__c();
        evt.Name = 'Test Old Event';
        evt.Live__c = true;
        evt.Start_Date_Time__c = datetime.newInstance(2020, 12, 25, 19, 30, 0);
        evt.End_Date_Time__c = datetime.newInstance(2020, 12, 26, 19, 30, 0);
        evt.Max_Seats__c = 50;

        insert evt;
        // System.debug('evt.Id == ' + evt.Id );
        return evt.Id;
    }
    //Creating Test Attendee
    static Id createTestAttendee(){
        Attendee__c att = new Attendee__c();
        att.Name = 'Test Attendee';
        insert att;
        return att.Id;
    }

    //Testing upcoming events
    @IsTest
    static void testUpcomingEvents(){
        Test.startTest();
        Event_Attendee__c eA = new Event_Attendee__c();
        eA.Event_Profit__c = createTestNewEvent();
        eA.Attendee__c = createTestAttendee();
        insert eA;

        Map<Id,Event_Attendee__c> retrievedEventAttn = new Map<Id,Event_Attendee__c>(AttendeeEventService_Two.getUpcomingEvents(eA.Attendee__c));
        // System.debug(retrievedEventAttn.containskey(eA.Id));
        Test.stopTest();

        System.assertEquals(True, retrievedEventAttn.containskey(eA.Id));
    }

    //Testing old events
    @IsTest
    static void testPastEvents(){
        Test.startTest();
        Event_Attendee__c eA = new Event_Attendee__c();
        eA.Event_Profit__c = createTestOldEvent();
        eA.Attendee__c = createTestAttendee();
        insert eA;

        Map<Id,Event_Attendee__c> retrievedEventAttn = new Map<Id,Event_Attendee__c>(AttendeeEventService_Two.getPastEvents(eA.Attendee__c));
        // System.debug(retrievedEventAttn.containskey(eA.Id));
        Test.stopTest();

        System.assertEquals(True, retrievedEventAttn.containskey(eA.Id));
    }
}