objects/Attendee__c.object
<CustomObject>
    <description>Record of all Attendee</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address of the Attendee</description>
        <inlineHelpText>ex. email@gmail.com</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the Attendees</description>
        <label>Location</label>
        <referenceTo>Location_Address_Book__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <description>Record of all Attendees in an event</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Attendee of the Event</description>
        <inlineHelpText>Select appropriate Event attendee</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_ProFit__c</fullName>
        <description>Defines the event</description>
        <inlineHelpText>Select appropriate Event</inlineHelpText>
        <label>Event(ProFit)</label>
        <referenceTo>Event_Profit__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Organizer__c.object
<CustomObject>
    <description>Record of all Event Organizers</description>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address of the Event Organizer</description>
        <inlineHelpText>ex. email@gmail.com</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the Event Organizer</description>
        <inlineHelpText>Select appropriate Location of the Event</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location_Address_Book__c</referenceTo>
        <relationshipLabel>Event Organizers</relationshipLabel>
        <relationshipName>Event_Organizers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the event</description>
        <inlineHelpText>Select the appropriate Event Location</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location_Address_Book__c</referenceTo>
        <relationshipLabel>Events(ProFit)</relationshipLabel>
        <relationshipName>Events_ProFit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organizer of the event</description>
        <inlineHelpText>Select the appropriate Organizer</inlineHelpText>
        <label>Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Location_Address_Book__c.object
<CustomObject>
    <description>Record of all Locations.(Address Book)</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City of the Address</description>
        <inlineHelpText>ex. Pasay City</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <description>Country of the Location</description>
        <inlineHelpText>ex. Philippines</inlineHelpText>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Afghanistan</fullName>
                </value>
                <value>
                    <fullName>Albania</fullName>
                </value>
                <value>
                    <fullName>Algeria</fullName>
                </value>
                <value>
                    <fullName>Andorra</fullName>
                </value>
                <value>
                    <fullName>Angola</fullName>
                </value>
                <value>
                    <fullName>Antigua and Barbuda</fullName>
                </value>
                <value>
                    <fullName>Argentina</fullName>
                </value>
                <value>
                    <fullName>Armenia</fullName>
                </value>
                <value>
                    <fullName>Australia</fullName>
                </value>
                <value>
                    <fullName>Austria</fullName>
                </value>
                <value>
                    <fullName>Azerbaijan</fullName>
                </value>
                <value>
                    <fullName>The Bahamas</fullName>
                </value>
                <value>
                    <fullName>Bahrain</fullName>
                </value>
                <value>
                    <fullName>Bangladesh</fullName>
                </value>
                <value>
                    <fullName>Barbados</fullName>
                </value>
                <value>
                    <fullName>Belarus</fullName>
                </value>
                <value>
                    <fullName>Belgium</fullName>
                </value>
                <value>
                    <fullName>Belize</fullName>
                </value>
                <value>
                    <fullName>Benin</fullName>
                </value>
                <value>
                    <fullName>Bhutan</fullName>
                </value>
                <value>
                    <fullName>Bolivia</fullName>
                </value>
                <value>
                    <fullName>Bosnia and Herzegovina</fullName>
                </value>
                <value>
                    <fullName>Botswana</fullName>
                </value>
                <value>
                    <fullName>Brazil</fullName>
                </value>
                <value>
                    <fullName>Brunei</fullName>
                </value>
                <value>
                    <fullName>Bulgaria</fullName>
                </value>
                <value>
                    <fullName>Burkina Faso</fullName>
                </value>
                <value>
                    <fullName>Burundi</fullName>
                </value>
                <value>
                    <fullName>Cambodia</fullName>
                </value>
                <value>
                    <fullName>Cameroon</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal Code of the Location</description>
        <inlineHelpText>ex. 1300</inlineHelpText>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State of the Location</description>
        <inlineHelpText>ex. Oklahoma</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street name of the address</description>
        <inlineHelpText>ex. Inocencio Street</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations(Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/SendEmailToAEventAttendee.cls
public with sharing class SendEmailToAEventAttendee {
    public static void sendConfirmationEmail(List<Event_Attendee__c> newRecordList ) {
        
        //Getting the AttendeeId and EventId for accessing the objects later
        Set<Id> attendeesIdsSet = new Set<Id>();
        Set<Id> eventIdsSet = new Set<Id>();
        
        for(Event_Attendee__c eAttn : newRecordList){
            attendeesIdsSet.add(eAttn.Attendee__c);
            eventIdsSet.add(eAttn.Event_Profit__c);
        }
        
        //getting all the needed information of the Attendee which is name and email
        Map<Id,Attendee__c> attendeeMap = new Map<Id,Attendee__c>( 
            [Select Id, Name, Email__c From Attendee__c WHERE  Id IN : attendeesIdsSet]
        );
        
        //getting all the information of the Event that are needed for the creation of email
        Map<Id, Event_Profit__c > eventMap = new Map<Id, Event_Profit__c > ( [Select Id, Name, Start_Date_Time__c, End_Date_Time__c, Organizer__c , Organizer__r.Name,Location__c , Location__r.Name, Location__r.City__c,Location__r.State__c, Location__r.Country__c,Location__r.Postal_Code__c, Location__r.Street__c FROM Event_Profit__c  WHERE ID IN: eventIdsSet]);
        
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        
        // Map<Id, Event_Attendee__c> evtmap = Map<Id, Event_Attendee__c>();

        for(Event_Attendee__c eAttn : newRecordList){
            
            Attendee__c attn = attendeeMap.get(eAttn.Attendee__c);
            Event_Profit__c evt = eventMap.get(eAttn.Event_Profit__c);
            
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

            mail.setSubject('Pass for the '+evt.Name);
            List<String> toEmailAddress = new List<String>();
            toEmailAddress.add(attn.Email__c);
            mail.setToAddresses( toEmailAddress );
            mail.setSenderDisplayName(evt.Organizer__r.Name);
            
            String loc = 'https://www.google.com/maps/place/'+evt.Location__r.Street__c+' '+evt.Location__r.City__c+' '
                +evt.Location__r.State__c+' '+
                evt.Location__r.Country__c+' '+evt.Location__r.Postal_Code__c;
            String hrefForLocation = '<a href="'+loc+'"'+'target="_blank">Here</a>';
            String eBody = 'Dear '+ attn.Name + ',<br/><br/>'+
                'Thank you for your registering for '+ evt.Name + ' which will be Organized on '+ evt.Start_Date_Time__c+' To '+evt.End_Date_Time__c+' & will be held in '+ evt.Location__r.Name+'. We are excited to have you, see you in the event.<br/><br/> Find the Google Map Location for the Event '+ hrefForLocation + '.<br/><br/><br/>'+
                'Thank you so much,<br/>'+evt.Organizer__r.Name;
            
            mail.setHtmlBody(eBody);
            emailList.add(mail); 
        }
        
        try{
            List<Messaging.SendEmailResult> results =  Messaging.sendEmail(emailList, false); 
            for(Messaging.SendEmailResult email : results){
                if(!email.isSuccess()){
                    List<Messaging.SendEmailError> errors = email.getErrors();
                }else{
                    System.debug('Email Succesfully Sent');
                }
            }  
        }catch(System.Exception ex){
            System.debug('Error Message: ' + ex);
        }
    }
}