objects/Attendee__c.object
<CustomObject>
    <description>Record of all Attendee</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the Attendees</description>
        <label>Location</label>
        <referenceTo>Location_Address_Book__c</referenceTo>
        <relationshipLabel>Attendees</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Event_Attendee__c.object
<CustomObject>
    <description>Record of all Attendees in an event</description>
    <fields>
        <fullName>Attendee__c</fullName>
        <description>Attendee of the Event</description>
        <inlineHelpText>Select appropriate Event attendee</inlineHelpText>
        <label>Attendee</label>
        <referenceTo>Attendee__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Event_ProFit__c</fullName>
        <description>Defines the event</description>
        <inlineHelpText>Select appropriate Event</inlineHelpText>
        <label>Event(ProFit)</label>
        <referenceTo>Event_Profit__c</referenceTo>
        <relationshipLabel>Event Attendees</relationshipLabel>
        <relationshipName>Event_Attendees</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Attendee</label>
    <nameField>
        <displayFormat>EA-{0000000}</displayFormat>
        <label>Event Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the event</description>
        <inlineHelpText>Select the appropriate Event Location</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location_Address_Book__c</referenceTo>
        <relationshipLabel>Events(ProFit)</relationshipLabel>
        <relationshipName>Events_ProFit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Location_Address_Book__c.object
<CustomObject>
    <description>Record of all Locations.(Address Book)</description>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations(Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AttendeeEventService_Two.cls
public with sharing class AttendeeEventService_Two {
    @AuraEnabled(cacheable=true)
    public static List<Event_Attendee__c> getUpcomingEvents(String attendeeId){
        List<Event_Attendee__c> query = [Select Id, Name, Event_ProFit__c, Event_ProFit__r.Start_Date_Time__c, Event_ProFit__r.End_Date_Time__c, Event_ProFit__r.Name, Event_ProFit__r.Location__r.Name from Event_Attendee__c where Attendee__c =: attendeeId and Event_ProFit__r.Start_Date_Time__c >= today];
        System.debug(query);
        return query;
    }

    @AuraEnabled(cacheable=true)
    public static List<Event_Attendee__c> getPastEvents(String attendeeId){
        List<Event_Attendee__c> query = [Select Id, Name, Event_ProFit__c, Event_ProFit__r.Start_Date_Time__c, Event_ProFit__r.End_Date_Time__c, Event_ProFit__r.Name, Event_ProFit__r.Location__r.Name from Event_Attendee__c where Attendee__c =: attendeeId and Event_ProFit__r.Start_Date_Time__c < today];
        System.debug(query);
        return query;
    }
}