objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Defines if the event is In-Person or Virtual</description>
        <inlineHelpText>Is the event happening in-person or virtual</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>Record of all speaker in an event</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Event Name</description>
        <inlineHelpText>Select appropriate Event Name</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event_Profit__c</referenceTo>
        <relationshipLabel>Event Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Name of event speaker</description>
        <inlineHelpText>Select appropriate speaker</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{0000000}</displayFormat>
        <label>Event Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <description>Record of all Speaker</description>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EventSpeakerChecker.cls
public with sharing class EventSpeakerChecker {
    public static void DuplicateEventSpeaker(List<Event_Speaker__c> newEvntSpeaker){
        try {

            Set<Id> eventID = new Set<Id>();
            Set<Id> eventSpeakerID = new Set<Id>();

            //putting the event ID and speaker ID in Sets
            for(Event_Speaker__c spk : newEvntSpeaker){
                eventID.add(spk.Event__c); 
                eventSpeakerID.add(spk.Speaker__c);
            }

            //Getting Event StartDate and EndDate of the new Event
            Event_Profit__c evtDate = [SELECT Start_Date_Time__c,End_Date_Time__c FROM Event_Profit__c WHERE Id IN: eventID];
                
            //Checking all the current events of the speakers and if the new event will have conflict within it.
            List<Event_Speaker__c> spkCount = [
            SELECT Id,Event__c,Speaker__c FROM Event_Speaker__c WHERE Speaker__c IN:eventSpeakerID
            AND((Event__r.Start_Date_Time__c < :evtDate.End_Date_Time__c AND Event__r.End_Date_Time__c > :evtDate.End_Date_Time__c) 
            OR(Event__r.Start_Date_Time__c < :evtDate.Start_Date_Time__c AND Event__r.End_Date_Time__c > :evtDate.Start_Date_Time__c)
            OR(Event__r.Start_Date_Time__c >= :evtDate.Start_Date_Time__c AND Event__r.End_Date_Time__c <= :evtDate.End_Date_Time__c))];                                                       

            //Record Start_Date_Time__c < Input End_Date_Time__c and Record End_Date_Time__c > Input End_Date_Time__c
            //OR Record Start_Date_Time__c < Input End_Date_Time__c and Record End_Date_Time__c > Input Start_Date_Time__c
            //OR Record Start_Date_Time__c < Input Start_Date_Time__c and Record End_Date_Time__c > Input End_Date_Time__c

            System.debug('spkCount.size() == ' + spkCount.size());
            
            //if theres a value in spkCount, it means that there's conflict with schedule
            for(Event_Speaker__c spk : newEvntSpeaker){
                if(spkCount.size()>0){
                    System.debug('The Speaker has already an event for this day.');
                    spk.Speaker__c.addError('The Speaker has already an event for this day.');
                }
            }
        }catch (Exception ex) {
            System.debug('Exception -- ' + ex.getMessage());
        }
    }
}