objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Defines if the event is In-Person or Virtual</description>
        <inlineHelpText>Is the event happening in-person or virtual</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if the event is Live</description>
        <inlineHelpText>Is event is Live or Not?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Maximum person for the event</description>
        <inlineHelpText>Maximum number of attendees for the event</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Speaker__c.object
<CustomObject>
    <description>Record of all speaker in an event</description>
    <fields>
        <fullName>Event__c</fullName>
        <description>Event Name</description>
        <inlineHelpText>Select appropriate Event Name</inlineHelpText>
        <label>Event</label>
        <referenceTo>Event_Profit__c</referenceTo>
        <relationshipLabel>Event Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <description>Name of event speaker</description>
        <inlineHelpText>Select appropriate speaker</inlineHelpText>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Event Speakers</relationshipLabel>
        <relationshipName>Event_Speakers</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Event Speaker</label>
    <nameField>
        <displayFormat>ES-{0000000}</displayFormat>
        <label>Event Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Event Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Speaker__c.object
<CustomObject>
    <description>Record of all Speaker</description>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>Company where the Speaker belong</description>
        <inlineHelpText>ex. ABC Company</inlineHelpText>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email Address of the Speaker</description>
        <inlineHelpText>ex. email@gmail.com</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Contact Number of the Speaker</description>
        <inlineHelpText>ex. 09672688171</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <label>Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EventSpeakerChecker_Test.cls
@isTest
private class EventSpeakerChecker_Test{
  Static Id createTestEventId(){
    
    //Mock Creation: New Event Record
    //and Fill-out all the required field
    Event_Profit__c evt = new Event_Profit__c();
    evt.Name = 'Test Event';
    evt.Live__c = true;
    evt.Max_Seats__c	= 50;
    evt.Start_Date_Time__c = datetime.newInstance(2021, 7, 21, 19, 30, 0);
    evt.End_Date_Time__c = datetime.newInstance(2021, 7, 22, 19, 30, 0);
    
    insert evt;
    System.debug('evt.Id == ' + evt.Id );
    return evt.Id;
  }
  
  Static Id createTestSpeakerId(){
  
    //Mock Creation: New Speaker Record
    Speaker__c spk = new Speaker__c();
    spk.Name = 'Test spk';
    spk.Email__c = 'test@gmail.com.ph';
    spk.Phone__c = '09672688177';
    spk.Company_Name__c = 'Test Company';
    insert spk;
    System.debug('spk.Id == ' + spk.Id );
    return spk.Id;
  }
  
  @IsTest 
  Static void checkEventSpeaker(){
    Test.startTest();
    
    //Creating a new Event-Speaker Record
    Event_Speaker__c eSpeak = new Event_Speaker__c();
    eSpeak.Event__c	= createTestEventId();
    eSpeak.Speaker__c = createTestSpeakerId();
    
    insert eSpeak;

    //Checking if the Test is successful by identifying if the inserted Id of the event
    //is equal to the output in retrievedESpeak.Event__c
    Event_Speaker__c retrievedESpeak = [SELECT Event__c FROM Event_Speaker__c WHERE Event__c =: eSpeak.Event__c];
    Test.stopTest();
  
    System.assertEquals(eSpeak.Event__c,retrievedESpeak.Event__c);
  }
}