objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Defines the status of the event</description>
        <inlineHelpText>Select the appropriate Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Post Poned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UpdateDeleteBatch.cls
public class UpdateDeleteBatch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext batchContext){
        //All query that are not completed, will be deleted
        //query = SELECT ALL Event that is not equal to "Complete" for the last 4 Months
        String query = 'SELECT Id, Name FROM Event_Profit__c WHERE Status__c != \'Complete\' AND End_Date_Time__c < LAST_N_MONTHS:4';
        return Database.getQueryLocator(query);
    }
    
    
    public void execute(Database.BatchableContext batchContext, List<Event_Profit__c> eventList ){

        //Process of updating status into deleted
        List<Event_Profit__c> willDelEvtList = new List<Event_Profit__c>();
        for(Event_Profit__c evt: eventList){
            evt.Status__c = 'Deleted';
            willDelEvtList.add(evt);
        }
        update willDelEvtList;
    }
    
    public void finish(Database.BatchableContext batchContext){

        String userName = UserInfo.getUserName();
        User activeUser = [Select Name,Email From User where Username = : userName limit 1];
        String userEmail = activeUser.Email;
        String actUserName = activeUser.Name;

        //Sending Email Processes
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();

        mail.setSubject('Batch Processing Completed');
        List<String> toAddress = new List<String>();
        toAddress.add(userEmail);
        mail.setToAddresses( toAddress );
        mail.setSenderDisplayName(actUserName);
        
        mail.setHtmlBody('Execution of the batch has been processed');
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage> {mail};
        Messaging.sendEmail(emails);
    }
}