objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Event__c</fullName>
        <description>Defines if the event is In-Person or Virtual</description>
        <inlineHelpText>Is the event happening in-person or virtual</inlineHelpText>
        <label>Event Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In-Person</fullName>
                </value>
                <value>
                    <fullName>Virtual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if the event is Live</description>
        <inlineHelpText>Is event is Live or Not?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Defines the status of the event</description>
        <inlineHelpText>Select the appropriate Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Post Poned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventDetailRestService_Test.cls
@istest
public with sharing class EventDetailRestService_Test {
    
    //Creating new Event
    static Id createEventTestRecord(){
        Event_ProFit__c evt = new Event_ProFit__c();
        evt.Name = 'Test Record REST Service';
        evt.Start_Date_Time__c = datetime.newInstance(2021, 6, 26, 11, 00, 0);
        evt.End_Date_Time__c = datetime.newInstance(2021, 6, 27, 12, 00, 0);
        evt.Event__c ='Virtual';
        evt.Live__c = true;
        evt.Status__c = 'Created';
        insert evt;
        return evt.Id;
    }

    //Testing the doGetEvt() by calling the event
    @IsTest
    static void doGetTest(){
        Test.startTest();
            Id eventId =  createEventTestRecord();
            RestRequest req = new RestRequest();
            req.requestURI = 'e-cmixrecords--sandboxpro.my.salesforce.com/services/apexrest/api/Event__c/'+EventId;
            req.httpMethod = 'GET';
            RestContext.request = req;
            Event_ProFit__c evt = EventDetailRestService.doGetEvt();
            System.assertEquals(eventId, evt.Id);
        Test.stopTest();
    }
}