objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if the event is Live</description>
        <inlineHelpText>Is event is Live or Not?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Max_Seats__c</fullName>
        <description>Maximum person for the event</description>
        <inlineHelpText>Maximum number of attendees for the event</inlineHelpText>
        <label>Max Seats</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Defines the status of the event</description>
        <inlineHelpText>Select the appropriate Status</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Post Poned</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
                <value>
                    <fullName>Deleted</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/UpdateDeleteBatch_Test.cls
@isTest
private class UpdateDeleteBatch_Test {

    public static testMethod void testUpdateBatch(){

        List<Event_Profit__c> eventList = new List<Event_Profit__c>();
        for(Integer i=0; i<100; i++){
            Event_Profit__c event = new Event_Profit__c(
                Name = 'Test Event No.'+i+1,
                Live__c = false,
                Status__c = 'Created',
                Max_Seats__c = 20,
                Start_Date_Time__c = datetime.newInstance(2020, 12, 1, 12, 0, 0),
                End_Date_Time__c  = datetime.newInstance(2020, 12, 4, 12, 0, 0)
            );
            eventList.add(event);
        }
        insert eventList;
        try{
            Test.startTest();

            UpdateDeleteBatch updel = new UpdateDeleteBatch();
            Database.executeBatch(updel,200);
            
            Test.stopTest();
        }catch (Exception ex){
            System.debug('Error Message: ' + ex);
        }
        System.AssertEquals(database.countquery('SELECT COUNT() From Event_Profit__c Where Status__c != \'Complete\''),100);  
    }
}