objects/Event_Organizer__c.object
<CustomObject>
    <description>Record of all Event Organizers</description>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the Event Organizer</description>
        <inlineHelpText>Select appropriate Location of the Event</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location_Address_Book__c</referenceTo>
        <relationshipLabel>Event Organizers</relationshipLabel>
        <relationshipName>Event_Organizers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Event_Profit__c.object
<CustomObject>
    <description>Record of all event</description>
    <fields>
        <fullName>End_Date_Time__c</fullName>
        <description>End Date and Time of the Event</description>
        <inlineHelpText>Select the exact ending Date and Time of the Event</inlineHelpText>
        <label>End Date/Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Live__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Defines if the event is Live</description>
        <inlineHelpText>Is event is Live or Not?</inlineHelpText>
        <label>Live?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Location of the event</description>
        <inlineHelpText>Select the appropriate Event Location</inlineHelpText>
        <label>Location</label>
        <referenceTo>Location_Address_Book__c</referenceTo>
        <relationshipLabel>Events(ProFit)</relationshipLabel>
        <relationshipName>Events_ProFit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Organizer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Organizer of the event</description>
        <inlineHelpText>Select the appropriate Organizer</inlineHelpText>
        <label>Organizer</label>
        <referenceTo>Event_Organizer__c</referenceTo>
        <relationshipName>Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date_Time__c</fullName>
        <description>Start Date and Time of the event</description>
        <inlineHelpText>Select the exact starting Date and Time of the Event</inlineHelpText>
        <label>Start Date/Time</label>
        <type>DateTime</type>
    </fields>
    <label>Event(ProFit)</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events(ProFit)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Location_Address_Book__c.object
<CustomObject>
    <description>Record of all Locations.(Address Book)</description>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations(Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/EventDetailRestService.cls
@RestResource(urlMapping = '/api/Event_Profit__c/*')
global with sharing class EventDetailRestService {
    @HTTPGet
    global static Event_Profit__c doGetEvt(){
        RestRequest req = RestContext.request;
        
        //Getting the evt Id after '/' *see at POSTMAN
        String evtId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);
        Event_Profit__c result = [Select Id, Name, Location__r.Name, Organizer__r.Name, Live__c, Start_Date_Time__c, End_Date_Time__c from Event_Profit__c where Id =: evtId];
        return result;
    }
}