objects/Location_Address_Book__c.object
<CustomObject>
    <description>Record of all Locations.(Address Book)</description>
    <fields>
        <fullName>City__c</fullName>
        <description>City of the Address</description>
        <inlineHelpText>ex. Pasay City</inlineHelpText>
        <label>City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <description>Postal Code of the Location</description>
        <inlineHelpText>ex. 1300</inlineHelpText>
        <label>Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <description>State of the Location</description>
        <inlineHelpText>ex. Oklahoma</inlineHelpText>
        <label>State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <description>Street name of the address</description>
        <inlineHelpText>ex. Inocencio Street</inlineHelpText>
        <label>Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code_Verified__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Zip Code Verified?</label>
        <type>Checkbox</type>
    </fields>
    <label>Location(Address Book)</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations(Address Book)</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/LocationAndZipVerifier.cls
public with sharing class LocationAndZipVerifier {
    @future (callout=true)

    //This will be called in Dev Console
    public static void zipVerifier(String locId) {
        Location_Address_Book__c loc = [Select Id,Zip_Code_Verified__c,State__c,Street__c,Postal_Code__c,City__c from Location_Address_Book__c where Id = :locId];

        //Basic HTTP Block
        Http httpzip = new Http();
        HttpRequest reqzip = new HttpRequest();
        String addzip = 'https://us-zipcode.api.smartystreets.com/lookup?auth-id=b5f1f399-ca32-c6fb-7b9d-7b1a8c8bab6b&auth-token=fKxFM43bq7BSAr2U9cgd&city=&state=&zipcode='+loc.Postal_Code__c;
        reqzip.setEndPoint(addzip);
        reqzip.setMethod('GET');
        HttpResponse respzip= new HttpResponse();
        respzip = httpzip.send(reqzip);


        try {
            if(respzip.getStatusCode() == 200){                                                         //check if the req is successful(code = 200)
                List<Object> resultsZipList = (List<Object>)JSON.deserializeUntyped(respzip.getBody()); //cast Response(JSON) into list of object
                for(Object obj : resultsZipList){                                                       //iterate all the object in list(resultsZipList)
                    Map<String, Object> results = (Map<String, Object>) obj;                            //cast the obj into MAP for easy data manipulation
                    System.debug('results==>'+results);
                    List<Object> zipObject = (List<Object>) results.get('zipcodes');                    //get the Id(zipcodes)
                    System.debug('zipObject==>'+zipObject);
                    if(zipObject!=null){                                                                //if the zipcode Obj != null then
                        LocationVerifier.locationVerifier(locId);                                      
                    }else{                                                                              //print the zipcode in debug
                        System.debug('ZipCode = ' + zipObject);
                        loc.Zip_Code_Verified__c = false;
                        update loc;
                    }
                }
            }
        } 
        
        catch (Exception ex) {
            System.debug('Exception -- ' + ex.getMessage());
        }
    }
}